/**
 * LLM Service - Google Gemini integration
 * 
 * CRITICAL: LLM only narrates decisions, NEVER makes them.
 * The verdict and confidence are already determined by rule-based scoring.
 * LLM transforms technical reasons into plain language for human review.
 * 
 * Using Gemini (free tier): https://ai.google.dev/
 * Get your API key at: https://makersuite.google.com/app/apikey
 */

import fetch from 'node-fetch';

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models';
const MODEL = 'gemini-1.5-flash'; // Fast, free tier available

/**
 * Generate plain-language commentary for a trading signal
 * @param {Object} signal - The computed signal with verdict, score, and reasons
 * @returns {Promise<Object>} Commentary object
 */
export async function generateCommentary(signal) {
  if (!GEMINI_API_KEY) {
    throw new Error('GEMINI_API_KEY not configured. Commentary unavailable.');
  }

  const prompt = buildPrompt(signal);
  
  try {
    const url = `${GEMINI_API_URL}/${MODEL}:generateContent?key=${GEMINI_API_KEY}`;
    
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.3, // Low temperature for consistency
          maxOutputTokens: 300,
          topK: 40,
          topP: 0.95,
        }
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini API error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    
    // Extract text from Gemini's response structure
    const commentaryText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!commentaryText) {
      throw new Error('No commentary text in Gemini response');
    }

    return {
      text: commentaryText.trim(),
      model: MODEL,
      disclaimer: 'This commentary is generated by AI and does not change the rule-based verdict or confidence score.',
      generatedAt: new Date().toISOString()
    };
  } catch (error) {
    console.error('LLM commentary generation failed:', error);
    throw error;
  }
}

/**
 * Build the prompt for LLM commentary
 * @param {Object} signal - Trading signal
 * @returns {string} Formatted prompt
 */
function buildPrompt(signal) {
  const reasonsList = signal.reasons
    .map(r => `- ${r.rule}: ${r.condition} (Score: ${r.score > 0 ? '+' : ''}${r.score}) - ${r.interpretation}`)
    .join('\n');

  return `You are a forex trading analyst explaining a technical analysis signal to a trader.

**Trading Signal for ${signal.pair}**

Verdict: ${signal.verdict}
Score: ${signal.score}
Confidence: ${signal.confidence.toFixed(1)}%

**Rules that fired:**
${reasonsList}

**Market snapshot:**
- Current price: ${signal.marketData.currentPrice.toFixed(4)}
- RSI(14): ${signal.marketData.rsi.toFixed(2)}
- MACD histogram: ${signal.marketData.macdHistogram.toFixed(6)}
- SMA(50): ${signal.marketData.sma50.toFixed(4)}
- Bollinger Bands: Upper ${signal.marketData.bollingerBands.upper.toFixed(4)} | Lower ${signal.marketData.bollingerBands.lower.toFixed(4)}

Write a concise 2-3 sentence plain-language summary explaining this ${signal.verdict} signal. Focus on:
1. What the key indicators are showing
2. Why the rules align (or don't align) for this verdict
3. Any important context about the current market state

Be direct and factual. Do not make predictions or add new analysis beyond what the rules already determined.`;
}
